@startuml
title Malaysian OSINT Query System - Flow Diagram

start

:Start HTTP Server;

while (Waiting for Request) is (true)
  :Receive HTTP GET Request;
  
  if (Request Parameter?) then (q)
    :Query PDRM Semak Mule;
    :Parse JSON Response;
    :Return Results;
  elseif (id) then
    :SSPI Identity Verification;
    :MyKad Info Query;
    :PDRM Wanted List Check;
    :SPRM Corruption Check;
    :Integrate All Results;
    :Return Results;
  elseif (name) then
    :E-Court Records Query;
    :Format JSON Response;
    :Return Results;
  elseif (ssm) then
    :Validate SSM Number Format;
    :Get Entity Type;
    :Return Results;
  else (invalid)
    :Return 400 Error;
  endif
  
  if (Shutdown Signal?) then (yes)
    break
  endif
endwhile

:Stop Server;

stop

@enduml