name: Release to GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmicrohttpd-dev libcjson-dev libcurl4-openssl-dev libssl-dev libsqlite3-dev libxml2-dev

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/mo
            LICENSE
            README.md
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}